import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Leffin - Portfolio",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/qje5ynx.css" />

      </head>
      <body>{children}</body>
    </html>
  );
}
