import type { Metadata } from "next";
import { Lato } from "next/font/google"
import "./globals.css";

export const metadata: Metadata = {
  title: "Leffin - Portfolio",
  description: "Generated by create next app",
};

export const lato = Lato({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lato.className}>
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/qje5ynx.css" />

      </head>
      <body>{children}</body>
    </html>
  );
}
